version: '3.8'
services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data